version: 2

project_name: typr

before:
  hooks:
    - go mod tidy

builds:
  - id: typr
    main: ./cmd/terminal-wpm
    binary: typr
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    builds:
      - typr
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - zip

checksum:
  name_template: checksums.txt

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

